### PR TITLE
Adding a WaitCondition for the Primary Node and Disable Realtime Windows Thread Detection during Installation

### PR DESCRIPTION
**Pull request by Optimiza**

### CODE REVIEW

**Comment by Optimiza** [comment]
Installation process:

```
2022-08-21 20:05:28,661 [DEBUG] CloudFormation client initialized ...
2022-08-21 20:28:24,200 P1284 [INFO] Completed successfully.
```

Using the WaitCondition we're returning the outputs after the installation finish, not just when the Windows Server is running.

`2022-08-21 20:29:24,693 [DEBUG] Signaling resource PrimaryNode in stack arn:aws:cloudformation:eu-central-1:940310827738:stack/X with unique ID X and status SUCCESS`

Install VRED tooks around 20 minutes to complete:

```
2022-08-21 20:05:30,881 [DEBUG] Running command a-install-vred
2022-08-21 20:05:30,881 [DEBUG] No test for command a-install-vred
2022-08-21 20:25:15,023 [INFO] Command a-install-vred succeeded
```

**Review by davmayd — DISMISSED** [review]

**Comment by Optimiza** [comment]
e2e test done with GP3 and InstanceProfile Changes

**Comment by Optimiza** [comment]
2022-08-22 05:12:33,010 [DEBUG] Running command a-install-vred
2022-08-22 05:12:33,010 [DEBUG] No test for command a-install-vred
2022-08-22 05:34:46,844 [INFO] Command a-install-vred succeeded

**Review by davmayd — DISMISSED** [review]

**Review by davmayd — APPROVED** [review]

**Pull request merged**
